name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'This release version (example 1.1.1)'
        required: true
        default: '1.x.x'
      nextVersion:
        description: 'Next version (example 1.1.2-SNAPSHOT)'
        required: true
        default: '1.x.x-SNAPSHOT'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.actor == 'flexca'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Release and Deploy
        run: |
          REPO_URL="https://github.com/${{ github.repository }}.git"

          mvn --batch-mode -Prelease release:prepare release:perform \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ github.event.inputs.nextVersion }} \
            -DpushChanges=true \
            -DlocalCheckout=true \
            -DscmCommentPrefix="[release] " \
            -Darguments="-DskipTests -Prelease" \
            -Dscm.url="scm:git:$REPO_URL" \
            -Dscm.developerUrl="scm:git:$REPO_URL"
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
